apiVersion: apps/v1
kind: Deployment
metadata:
  name: handbrake
  labels:
    app: handbrake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: handbrake
  template:
    metadata:
      labels:
        app: handbrake
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config-pvc
        - name: storage
          persistentVolumeClaim:
            claimName: storage-pvc
        - name: watch
          persistentVolumeClaim:
            claimName: watch-pvc
        - name: output
          persistentVolumeClaim:
            claimName: output-pvc
      containers:
      - name: handbrake
        image: jlesage/handbrake
        ports:
        - containerPort: 5800
        env:
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 8 }}
          {{- end }}
        volumeMounts:
          - name: config
            mountPath: /config
          - name: storage
            mountPath: /storage
          - name: watch
            mountPath: /watch
          - name: output
            mountPath: /output
