apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert.gardener.cloud/purpose: managed
    dns.gardener.cloud/class: garden
    dns.gardener.cloud/dnsnames: {{ .Values.clusterName }}
    dns.gardener.cloud/ttl: "180"
  labels:
    app: handbrake
  name: handbrake
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.clusterName }}
    http:
      paths:
      - backend:
          service:
            name: handbrake
            port:
              number: 5800
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.clusterName }}
    secretName: demo-tls-secret
